.PHONY: clean All

All:
	@echo "----------Building project:[ EscherEncryption - Release ]----------"
	@$(MAKE) -f  "EscherEncryption.mk"
clean:
	@echo "----------Cleaning project:[ EscherEncryption - Release ]----------"
	@$(MAKE) -f  "EscherEncryption.mk" clean
